encoding: UTF-8

exclude:
  - index.bat

excerpt_separator: <!--more-->

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
